Repository jupyterlab-contrib/jupyter-suggestions, pull requests merged in 2024-12, with the labels that each got.

#8 Save suggestions to notebook metadata
  packages/base/package.json
  packages/base/src/icons.ts
  packages/base/src/localSuggestionsManager/localSuggestionsManager.ts
  packages/base/src/suggestionsPanel/cellWidget.ts
  packages/base/src/suggestionsPanel/cmExtension.ts
  packages/base/src/suggestionsPanel/model.ts
  packages/base/src/suggestionsPanel/style.ts
  packages/base/src/suggestionsPanel/suggestionWidget/cellWidget.ts
  packages/base/src/suggestionsPanel/suggestionWidget/index.ts
  packages/base/src/suggestionsPanel/suggestionWidget/style.ts
  packages/base/src/suggestionsPanel/suggestionWidget/suggestionToolbar.tsx
  packages/base/src/suggestionsPanel/widget.ts
  packages/base/src/types.ts
  packages/base/style/icon/collapse.svg
  packages/base/style/icon/expand.svg
  packages/base/style/icon/minimize.svg
  tsconfigbase.json
  yarn.lock
Labels: enhancement

#16 Remove workaround for the browser check
  .github/workflows/build.yml
Labels: maintenance

#13 Handle cell deletion and cell move
  packages/base/package.json
  packages/base/src/baseSuggestionsManager.ts
  packages/base/src/index.ts
  packages/base/src/localSuggestionsManager/localSuggestionsManager.ts
  packages/base/src/suggestionsPanel/model.ts
  packages/base/src/suggestionsPanel/panel.ts
  packages/base/src/suggestionsPanel/suggestionWidget/cellWidget.ts
  packages/base/src/suggestionsPanel/suggestionWidget/style.ts
  packages/base/src/suggestionsPanel/suggestionWidget/suggestionToolbar.tsx
  packages/base/src/suggestionsPanel/widget.ts
  packages/base/src/tools.ts
  packages/base/src/types.ts
  python/jupyter_suggestions_core/src/plugins.ts
  python/jupyter_suggestions_rtc/package.json
  python/jupyter_suggestions_rtc/src/manager.ts
  yarn.lock
Labels: enhancement

#15 Support cell deletion suggestions
  package.json
  packages/base/src/baseSuggestionsManager.ts
  packages/base/src/icons.ts
  packages/base/src/index.ts
  packages/base/src/localSuggestionsManager/localSuggestionsManager.ts
  packages/base/src/suggestionCellMenu/cellToolbarMenu.tsx
  packages/base/src/suggestionCellMenu/index.ts
  packages/base/src/suggestionCellMenu/style.ts
  packages/base/src/suggestionsPanel/model.ts
  packages/base/src/suggestionsPanel/suggestionWidget/baseWidget.ts
  packages/base/src/suggestionsPanel/suggestionWidget/changeCellWidget.ts
  packages/base/src/suggestionsPanel/suggestionWidget/deleteCellWidget.ts
  packages/base/src/suggestionsPanel/suggestionWidget/index.ts
  packages/base/src/suggestionsPanel/suggestionWidget/style.ts
  packages/base/src/suggestionsPanel/suggestionWidget/suggestionToolbar.tsx
  packages/base/src/suggestionsPanel/widget.ts
  packages/base/src/tools.ts
  packages/base/src/types.ts
  packages/base/style/icon/cross.svg
  packages/base/style/icon/location.svg
  python/jupyter_suggestions_core/package.json
  python/jupyter_suggestions_core/schema/commands.json
  python/jupyter_suggestions_core/src/index.ts
  python/jupyter_suggestions_core/src/plugins.ts
  python/jupyter_suggestions_rtc/src/manager.ts
  yarn.lock
Labels: enhancement

#22 Add a screenshot to the README
  README.md
  jupyter-suggestions.png
Labels: documentation

#23 Update links to the repo
  .copier-answers.yml
  CONTRIBUTING.md
  LICENSE
  README.md
  package.json
  packages/base/package.json
  python/jupyter_suggestions/LICENSE
  python/jupyter_suggestions_core/package.json
  python/jupyter_suggestions_rtc/LICENSE
  python/jupyter_suggestions_rtc/package.json
Labels: maintenance

#17 Add UI tests
  .eslintignore
  .github/workflows/build.yml
  .gitignore
  packages/base/src/suggestionCellMenu/cellToolbarMenu.tsx
  python/jupyter_suggestions_core/style/base.css
  ui-tests/jupyter_server_test_config.py
  ui-tests/package.json
  ui-tests/playwright.config.js
  ui-tests/tests/notebooks/test.ipynb
  ui-tests/tests/ui.spec.ts
  ui-tests/tests/ui.spec.ts-snapshots/local-accept-change-suggestion-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/local-accept-delete-suggestion-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/local-add-suggestion-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/local-change-cell-content-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/local-main-page-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/local-side-panel-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/rtc-accept-change-suggestion-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/rtc-accept-delete-suggestion-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/rtc-add-suggestion-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/rtc-change-cell-content-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/rtc-main-page-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/rtc-side-panel-linux.png
  ui-tests/yarn.lock
Labels: maintenance

#21 Update to JupyterLab 0.5.0 pre-release
  .github/workflows/build.yml
Labels: maintenance

#27 Fix deleting last cell
  packages/base/src/localSuggestionsManager/localSuggestionsManager.ts
  packages/base/src/suggestionsPanel/model.ts
  packages/base/src/tools.ts
  yarn.lock
Labels: bug

#28 Update readme
  CONTRIBUTING.md
  README.md
  assets/jupyter-suggestions.png
  jupyter-suggestions.png
  yarn.lock
Labels: documentation
